### ISSUE TITLE
Analysis screen - v1

### ISSUE THREAD

**Issue by delirehberi** [workouse/referral-marketing-sylius#5]
**Description**  

Report screens about the usage of the referral system by users in the admin panel could be awesome. 
the first version must be a response to these questions: 
- Which users sent invitations?
- How many invitations sending by which user?
- How many invitations accepted?
- How many invitations rejected?
- Which users register after receiving an invitation?

We can discuss this feature. @bykclk @amaeksi

**Comment by bykclk** [comment]
https://github.com/workouse/referral-marketing-sylius/commit/bb18cf9897a4a1f54cd6e77d56f1963dd146235e
